<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /** Uniquement les images que vous fournissez (clé "image" dans chaque produit). Aucune image par défaut. */
    public function run(): void
    {
        $categories = Category::all()->keyBy('slug');
        if ($categories->isEmpty()) {
            return;
        }

        $yeux = $categories->get('yeux');
        if ($yeux) {
            Product::where('category_id', $yeux->id)->delete();
        }

        $ongles = $categories->get('ongles');
        if ($ongles) {
            Product::where('category_id', $ongles->id)->delete();
        }

        $accessoires = $categories->get('accessoires');
        if ($accessoires) {
            Product::where('category_id', $accessoires->id)->delete();
        }

        Product::whereIn('slug', [
            'rouge-levres-mat-velvet',
            'fond-de-teint-fluide-24h',
            'palette-yeux-12-nuances',
            'mascara-volume-intense',
            'eyeliner-liquide-waterproof',
        ])->delete();

        $products = [
            ['name' => 'Rouge à Lèvres Mat GUCCI – Nuance Rose Ancien', 'slug' => 'rouge-levres-mat-gucci-rose-ancien', 'category' => 'levres', 'description' => 'Rouge à lèvres mat finition veloutée, nuance rose ancien élégant. Étui doré cannelé signature GUCCI. Formule longue tenue et confortable.', 'price' => 55.00, 'sale_price' => null, 'sku' => 'LIP-001', 'stock' => 45, 'is_featured' => true, 'image' => 'images/products/levres-1.png'],
            ['name' => 'Rouge à Lèvres L\'Oréal Paris – Rouge Classique', 'slug' => 'rouge-levres-loreal-paris-rouge-classique', 'category' => 'levres', 'description' => 'Rouge à lèvres fini crème, rouge intense et lumineux. Tenue confortable et pigmentation haute. Tube doré signature L\'Oréal Paris.', 'price' => 14.99, 'sale_price' => 12.99, 'sku' => 'LIP-002', 'stock' => 120, 'is_featured' => true, 'image' => 'images/products/levres-2.png'],
            ['name' => 'Kit Lèvres MAC – Rouge Crème Nude Rosé & Crayon', 'slug' => 'kit-levres-mac-nude-rose-crayon', 'category' => 'levres', 'description' => 'Rouge à lèvres crème nude rosé et crayon contour des lèvres assorti. Look nude parfait et tenue longue durée. Packaging rose gold MAC.', 'price' => 42.00, 'sale_price' => null, 'sku' => 'LIP-003', 'stock' => 60, 'is_featured' => true, 'image' => 'images/products/levres-3.png'],
            ['name' => 'Baume à Lèvres Teinté Hydratant Palladio', 'slug' => 'baume-levres-teinte-hydratant-palladio', 'category' => 'levres', 'description' => 'Crayon baume teinté hydratant et nourrissant. Teinte rosé naturel, formule non collante. Idéal pour un effet bonne mine au quotidien.', 'price' => 14.90, 'sale_price' => null, 'sku' => 'LIP-004', 'stock' => 95, 'is_featured' => false, 'image' => 'images/products/levres-4.png'],
            ['name' => 'Gloss Brillant Pêche Corail', 'slug' => 'gloss-brillant-peche-corail', 'category' => 'levres', 'description' => 'Gloss ultra brillant effet miroir, teinte pêche corail. Lèvres pulpeuses et lumineuses. Formule hydratante et confortable.', 'price' => 24.00, 'sale_price' => null, 'sku' => 'LIP-005', 'stock' => 80, 'is_featured' => true, 'image' => 'images/products/levres-5.png'],
            ['name' => 'Collection Gloss Lèvres USHAS – 6 nuances', 'slug' => 'collection-gloss-levres-ushas', 'category' => 'levres', 'description' => 'Set de gloss USHAS en 6 teintes nude, rose, pêche et brun rosé. Finis brillant et pailleté. Tubes à bouchon doré cannelé.', 'price' => 12.99, 'sale_price' => null, 'sku' => 'LIP-006', 'stock' => 70, 'is_featured' => false, 'image' => 'images/products/levres-6.png'],
            ['name' => 'Gloss Éclat Scintillant Rose Mystère', 'slug' => 'gloss-eclat-scintillant-rose-mystere', 'category' => 'levres', 'description' => 'Gloss scintillant rose mystère, finition miroir et particules lumineuses. Bouchon cuivré rosé. Effet glamour et hydratation intense.', 'price' => 24.99, 'sale_price' => 21.99, 'sku' => 'LIP-007', 'stock' => 55, 'is_featured' => true, 'image' => 'images/products/levres-7.png'],
            ['name' => 'Gloss Sarah\'s Beauty – Fuchsia & Corail Scintillant', 'slug' => 'gloss-sarahs-beauty-fuchsia-corail', 'category' => 'levres', 'description' => 'Duo de gloss scintillants : fuchsia intense et rouge corail. Brilho labial haute brillance. Bouchons argentés élégants.', 'price' => 22.00, 'sale_price' => null, 'sku' => 'LIP-008', 'stock' => 65, 'is_featured' => false, 'image' => 'images/products/levres-8.png'],
            ['name' => 'Kit Teint Professionnel 15 Nuances – Correcteur & Anti-Cernes', 'slug' => 'kit-teint-pro-15-nuances-correcteur', 'category' => 'teint', 'description' => 'Palette professionnelle 15 teintes crème pour correction, anti-cernes, contouring et highlight. Texture fond de teint et correcteur, applicateur double pointe inclus.', 'price' => 49.99, 'sale_price' => null, 'sku' => 'TEINT-001', 'stock' => 40, 'is_featured' => true, 'image' => 'images/products/teint-1.png'],
            ['name' => 'L\'Oréal Paris Nude Magique Eau de Teint', 'slug' => 'loreal-paris-nude-magique-eau-de-teint', 'category' => 'teint', 'description' => 'Fond de teint fluide légère couvrance, fini naturel. Formule fraîche et confortable. Pompe précise, flacon verre.', 'price' => 15.99, 'sale_price' => null, 'sku' => 'TEINT-002', 'stock' => 90, 'is_featured' => false, 'image' => 'images/products/teint-2.png'],
            ['name' => 'Shiseido Sheer and Perfect Foundation Teint Naturel', 'slug' => 'shiseido-sheer-perfect-foundation', 'category' => 'teint', 'description' => 'Fond de teint fluide Shiseido à la texture légère et parfaite. Teint naturel et lumineux. Flacon élégant bouchon noir.', 'price' => 45.00, 'sale_price' => null, 'sku' => 'TEINT-003', 'stock' => 35, 'is_featured' => true, 'image' => 'images/products/teint-3.png'],
            ['name' => 'Poudre Compacte Matifiante SACE LADY', 'slug' => 'poudre-compacte-matifiante-sace-lady', 'category' => 'teint', 'description' => 'Poudre compacte teint naturel, fini mat et velouté. Boîtier noir à couvercle transparent. Texture fine pour un teint parfait.', 'price' => 34.99, 'sale_price' => null, 'sku' => 'TEINT-004', 'stock' => 55, 'is_featured' => false, 'image' => 'images/products/teint-4.png'],
            ['name' => 'Collection Poudres Lumière Teint Éclatant – 4 Nuances', 'slug' => 'collection-poudres-lumiere-teint-eclatant', 'category' => 'teint', 'description' => 'Quatre poudres compactes rose gold : beige, rose, ivoire et bronze. Fixation et luminosité. Miroir intégré.', 'price' => 34.99, 'sale_price' => 29.99, 'sku' => 'TEINT-005', 'stock' => 45, 'is_featured' => true, 'image' => 'images/products/teint-5.png'],
            ['name' => 'Set Teint Pro – Poudre, Blush Marbré & Pinceau Laura Geller', 'slug' => 'set-teint-pro-poudre-blush-laura-geller', 'category' => 'teint', 'description' => 'Poudre compacte fini mat, blush illuminateur marbré rose et pinceau professionnel duo fibre. Look teint parfait complet.', 'price' => 42.00, 'sale_price' => null, 'sku' => 'TEINT-006', 'stock' => 30, 'is_featured' => true, 'image' => 'images/products/teint-6.png'],
            ['name' => 'Palette Teint Contour, Blush & Highlighter', 'slug' => 'palette-teint-contour-blush-highlighter', 'category' => 'teint', 'description' => 'Palette visage trois zones : contour brun, blush rose et highlighter pêche. Guide d\'application inclus pour un maquillage pro.', 'price' => 39.99, 'sale_price' => null, 'sku' => 'TEINT-007', 'stock' => 50, 'is_featured' => false, 'image' => 'images/products/teint-7.png'],
            ['name' => 'Hengfang Magic Skin Beautiful BB Beauty Booster', 'slug' => 'hengfang-bb-beauty-booster', 'category' => 'teint', 'description' => 'BB crème hydratante correctrice, SPF large spectre. 3 teintes disponibles. Effet bonne mine et couvrance légère. 35 ml.', 'price' => 24.99, 'sale_price' => null, 'sku' => 'TEINT-008', 'stock' => 65, 'is_featured' => false, 'image' => 'images/products/teint-8.png'],
            ['name' => 'MAKE UP FOR EVER Matte Velvet Skin Anti-Cernes Haute Couvrance', 'slug' => 'make-up-for-ever-matte-velvet-anti-cernes', 'category' => 'teint', 'description' => 'Anti-cernes multi-usages haute couvrance, fini mat velours. Tenue 24h. Applicateur doe-foot. Formule professionnelle.', 'price' => 29.00, 'sale_price' => null, 'sku' => 'TEINT-009', 'stock' => 60, 'is_featured' => true, 'image' => 'images/products/teint-9.png'],
            ['name' => 'Correcteur Professionnel MAKE UP FOR EVER – Stick', 'slug' => 'correcteur-pro-make-up-for-ever-stick', 'category' => 'teint', 'description' => 'Correcteur stick professionnel, fini naturel éclatant. Format précis pour cernes et imperfections. Teinte beige clair.', 'price' => 24.99, 'sale_price' => 21.99, 'sku' => 'TEINT-010', 'stock' => 55, 'is_featured' => false, 'image' => 'images/products/teint-10.png'],
            ['name' => 'Stick Illuminateur et Contour Double Usage', 'slug' => 'stick-illuminateur-contour-double-usage', 'category' => 'teint', 'description' => 'Bâtonnet double usage : highlight et contour. Sculpture du visage et luminosité. Application facile, effet pro.', 'price' => 35.00, 'sale_price' => null, 'sku' => 'TEINT-011', 'stock' => 45, 'is_featured' => true, 'image' => 'images/products/teint-11.png'],
            ['name' => 'Mascara Waterproof Super Fit Colors – Noir & Couleurs', 'slug' => 'mascara-waterproof-super-fit-colors', 'category' => 'yeux', 'description' => 'Mascara waterproof noir et couleurs (blanc, bleu, vert, violet, orange, rouge). Brosses précises, tenue longue. Idéal pour looks créatifs.', 'price' => 14.99, 'sale_price' => null, 'sku' => 'EYE-001', 'stock' => 75, 'is_featured' => true, 'image' => 'images/products/yeux-1.png'],
            ['name' => 'Crayon Eyeliner Rétractable Avon True Colour – Gris Anthracite', 'slug' => 'crayon-eyeliner-avon-true-colour-gris', 'category' => 'yeux', 'description' => 'Crayon eyeliner rétractable précision, teinte gris anthracite. Application nette, effet smudge possible. Format Avon True Colour.', 'price' => 12.99, 'sale_price' => null, 'sku' => 'EYE-002', 'stock' => 80, 'is_featured' => false, 'image' => 'images/products/yeux-2.png'],
            ['name' => 'Collection Crayons Yeux Précision – 10 Nuances', 'slug' => 'collection-crayons-yeux-precision-10-nuances', 'category' => 'yeux', 'description' => 'Set de 10 crayons yeux : noir, brun, rose nude, magenta, vert, bleu royal, brun chocolat, prune, argent et bleu. Pour traits et fards.', 'price' => 29.99, 'sale_price' => null, 'sku' => 'EYE-003', 'stock' => 45, 'is_featured' => true, 'image' => 'images/products/yeux-3.png'],
            ['name' => 'Baolishi Duo Sticks Smoky Eye Effect – 6 Nuances', 'slug' => 'baolishi-duo-sticks-smoky-eye-effect', 'category' => 'yeux', 'description' => 'Six bâtons doubles (Step 1 & 2) effet smoky : noir/blanc, violet/or, cuivre/blanc, cuivre/or, noir/bleu, blanc/prune. Application facile.', 'price' => 24.99, 'sale_price' => 21.99, 'sku' => 'EYE-004', 'stock' => 55, 'is_featured' => true, 'image' => 'images/products/yeux-4.png'],
            ['name' => 'Collection Paillettes Yeux FLARE – 10 Teintes', 'slug' => 'collection-paillettes-yeux-flare', 'category' => 'yeux', 'description' => 'Coffret 10 flacons paillettes FLARE : argent, or, cuivre, rose gold, vert olive. Effet scintillant pour regard glamour. Applicateur inclus.', 'price' => 32.00, 'sale_price' => null, 'sku' => 'EYE-005', 'stock' => 40, 'is_featured' => false, 'image' => 'images/products/yeux-5.png'],
            ['name' => 'Shadow Stick & Smudger Scintillant Cuivré Rose Doré', 'slug' => 'shadow-stick-smudger-cuivre-rose-dore', 'category' => 'yeux', 'description' => 'Bâton double : ombre scintillante cuivrée rose doré et estompeur en mousse. Look smoky facile. Finition luxe or.', 'price' => 34.99, 'sale_price' => null, 'sku' => 'EYE-006', 'stock' => 50, 'is_featured' => true, 'image' => 'images/products/yeux-6.png'],
            ['name' => 'Palette Ombres Nudabeauty Pastel Corals – 18 Teintes', 'slug' => 'palette-ombres-nudabeauty-pastel-corals', 'category' => 'yeux', 'description' => 'Palette 18 ombres mat, satin et pailleté : pêche, rose, mauve, or et bronze. Thème Pastel Corals. Boîtier Nudabeauty.', 'price' => 44.99, 'sale_price' => null, 'sku' => 'EYE-007', 'stock' => 35, 'is_featured' => true, 'image' => 'images/products/yeux-7.png'],
            ['name' => 'Palette Nádia Tambasco Oceane – 8 Ombres', 'slug' => 'palette-nadia-tambasco-oceane', 'category' => 'yeux', 'description' => 'Palette 8 teintes Nádia Tambasco Oceane : Blanc, Starlet, Honey Lust, Celestial, Brownie, Glow, Cosmic, Meteorite. Finitions scintillantes.', 'price' => 39.99, 'sale_price' => null, 'sku' => 'EYE-008', 'stock' => 42, 'is_featured' => false, 'image' => 'images/products/yeux-8.png'],
            ['name' => 'Palette Ombres à Paupières Nude Rosé – 8 Teintes', 'slug' => 'palette-ombres-paupieres-nude-rose', 'category' => 'yeux', 'description' => 'Palette 8 ombres nude et rosé : mat, satin et pailleté. Miroir et applicateur double pointe inclus. Look naturel ou smokey doux.', 'price' => 34.99, 'sale_price' => 29.99, 'sku' => 'EYE-009', 'stock' => 58, 'is_featured' => true, 'image' => 'images/products/yeux-9.png'],
            ['name' => 'Gel Eyeliner Teinte Nude & Pinceau Double', 'slug' => 'gel-eyeliner-teinte-nude-pinceau', 'category' => 'yeux', 'description' => 'Gel eyeliner teinte nude/brun clair, pot verre. Pinceau double pointe (angle + fin) pour trait précis. Tenue longue, effet naturel ou graphique.', 'price' => 22.00, 'sale_price' => null, 'sku' => 'EYE-010', 'stock' => 65, 'is_featured' => false, 'image' => 'images/products/yeux-10.png'],
            ['name' => 'Duo Ombre à Paupières Liquide Or Scintillant & Mat Brun', 'slug' => 'duo-ombre-paupieres-liquide-or-brun', 'category' => 'yeux', 'description' => 'Double fard à paupières liquide : une extrémité or scintillant, l\'autre brun mat. Applicateur doe-foot. Looks glamour ou nude.', 'price' => 28.99, 'sale_price' => null, 'sku' => 'EYE-011', 'stock' => 48, 'is_featured' => true, 'image' => 'images/products/yeux-11.png'],
            ['name' => 'Collection Mascaras Maybelline New York – 5 Effets', 'slug' => 'collection-mascaras-maybelline-5-effets', 'category' => 'yeux', 'description' => 'Sélection Maybelline : Lash Sensational, The Falsies Volum\'Express Waterproof, Luscious Full Fan, Colossal Hydrofuge, Push Up Drama. Cils XXL.', 'price' => 12.99, 'sale_price' => null, 'sku' => 'EYE-012', 'stock' => 90, 'is_featured' => true, 'image' => 'images/products/yeux-12.png'],
            ['name' => 'Eyeliner Liquide MAKE UP FACTORY – Bleu Saphir', 'slug' => 'eyeliner-liquide-make-up-factory-bleu', 'category' => 'yeux', 'description' => 'Eyeliner liquide intense bleu saphir. Pointe applicateur précise, bouteille noire. Effet électrique pour regard signature.', 'price' => 16.99, 'sale_price' => 14.99, 'sku' => 'EYE-013', 'stock' => 70, 'is_featured' => false, 'image' => 'images/products/yeux-13.png'],
            ['name' => 'Rimmel London Super Gel – Étape 1 010 Chill Out', 'slug' => 'rimmel-super-gel-010-chill-out', 'category' => 'ongles', 'description' => 'Vernis gel effet miroir, teinte gris mauve neutre. Étape 1 du système Super Gel. Longue tenue et brillance.', 'price' => 8.99, 'sale_price' => null, 'sku' => 'NAIL-001', 'stock' => 120, 'is_featured' => true, 'image' => 'images/products/ongles-1.png'],
            ['name' => 'Golden Rose Extreme Gel Shine – Vernis à ongles', 'slug' => 'golden-rose-extreme-gel-shine', 'category' => 'ongles', 'description' => 'Vernis gel brillant teinte mauve rosé. Finition ultra brillante et tenue longue durée. Flacon verre bouchon noir.', 'price' => 7.99, 'sale_price' => null, 'sku' => 'NAIL-002', 'stock' => 95, 'is_featured' => false, 'image' => 'images/products/ongles-2.png'],
            ['name' => 'NC NAILS GELIQUE Tan Body – Effet métallisé rose nude', 'slug' => 'nc-nails-gelique-tan-body', 'category' => 'ongles', 'description' => 'Vernis gel effet métallisé rose nude scintillant. 6 ml. Finition miroir et reflets rosés. NC NAILS company.', 'price' => 14.99, 'sale_price' => null, 'sku' => 'NAIL-003', 'stock' => 60, 'is_featured' => true, 'image' => 'images/products/ongles-3.png'],
            ['name' => 'NC NAILS GELIQUE Mirage 333 – Violet pailleté holographique', 'slug' => 'nc-nails-gelique-mirage-333', 'category' => 'ongles', 'description' => 'Vernis gel violet intense à paillettes multicolores. Effet holographique. 6 ml. Flacon noir bouchon rose gold.', 'price' => 14.99, 'sale_price' => 12.99, 'sku' => 'NAIL-004', 'stock' => 55, 'is_featured' => true, 'image' => 'images/products/ongles-4.png'],
            ['name' => 'Chanel Le Vernis Immortelle 135 – Lavande pastel', 'slug' => 'chanel-le-vernis-immortelle-135', 'category' => 'ongles', 'description' => 'Vernis à ongles Chanel teinte lavande pastel. Finition brillante et élégante. Flacon signature verre noir.', 'price' => 32.00, 'sale_price' => null, 'sku' => 'NAIL-005', 'stock' => 40, 'is_featured' => true, 'image' => 'images/products/ongles-5.png'],
            ['name' => 'Chanel Le Vernis 757 Rose Fusion – Rose or métallique', 'slug' => 'chanel-le-vernis-757-rose-fusion', 'category' => 'ongles', 'description' => 'Vernis nail colour Chanel teinte rose fusion, reflets bronze et rose gold. Finition métallique scintillante.', 'price' => 32.00, 'sale_price' => null, 'sku' => 'NAIL-006', 'stock' => 38, 'is_featured' => true, 'image' => 'images/products/ongles-6.png'],
            ['name' => 'BZ Lady Lady Laque à ongles – Gris bleuté', 'slug' => 'bz-lady-lady-nail-lacquer', 'category' => 'ongles', 'description' => 'Laque à ongles 15 ml teinte gris clair bleuté. Finition brillante. Marque BZ Lady Lady.', 'price' => 9.99, 'sale_price' => null, 'sku' => 'NAIL-007', 'stock' => 80, 'is_featured' => false, 'image' => 'images/products/ongles-7.png'],
            ['name' => 'Olive & June Quick Dry – Vernis séchage rapide gris nude', 'slug' => 'olive-june-quick-dry', 'category' => 'ongles', 'description' => 'Vernis séchage rapide teinte gris nude. Formule Quick Dry. Finition glossy. Flacon verre bouchon blanc.', 'price' => 12.99, 'sale_price' => null, 'sku' => 'NAIL-008', 'stock' => 70, 'is_featured' => false, 'image' => 'images/products/ongles-8.png'],
            ['name' => 'Beauty People Quick Dry Illuminate Me – Mauve lumineux', 'slug' => 'beauty-people-quick-dry-illuminate-me', 'category' => 'ongles', 'description' => 'Vernis à ongles Quick Dry teinte mauve clair. Nail Enamel 12 ml. Formule d\'origine France.', 'price' => 11.99, 'sale_price' => null, 'sku' => 'NAIL-009', 'stock' => 65, 'is_featured' => false, 'image' => 'images/products/ongles-9.png'],
            ['name' => 'Beauty People Velvet Matte – Laque mate nude pêche', 'slug' => 'beauty-people-velvet-matte', 'category' => 'ongles', 'description' => 'Laque à ongles mate teinte nude pêche. Finition velours mat. 9,9 ml. BEAUTY PEOPLE®.', 'price' => 11.99, 'sale_price' => null, 'sku' => 'NAIL-010', 'stock' => 58, 'is_featured' => false, 'image' => 'images/products/ongles-10.png'],
            ['name' => 'Rosalind Gel Polish Professional – Palette 12 teintes', 'slug' => 'rosalind-gel-polish-professional', 'category' => 'ongles', 'description' => 'Vernis gel professionnel Rosalind. Large palette : blanc, rose, nude, terracotta, mauve, gris, brun, paillettes. Flacons 6 ml.', 'price' => 24.99, 'sale_price' => 21.99, 'sku' => 'NAIL-011', 'stock' => 45, 'is_featured' => true, 'image' => 'images/products/ongles-11.png'],
            ['name' => 'Ongles en gel French Manucure – Blanc et noir', 'slug' => 'ongles-gel-french-manucure', 'category' => 'ongles', 'description' => 'Set d\'ongles en gel style French manucure : base nude avec pointes blanches ou pointes noires. Coffret présentation soignée.', 'price' => 7.99, 'sale_price' => null, 'sku' => 'NAIL-012', 'stock' => 90, 'is_featured' => false, 'image' => 'images/products/ongles-12.png'],
            ['name' => 'Ongles pressés – Rose, pêche et nude pailleté', 'slug' => 'ongles-presses-rose-peche-nude', 'category' => 'ongles', 'description' => 'Ongles artificiels coffret : rose pêche translucide, rose baby pailleté, nude terracotta. Forme coffin, fini brillant.', 'price' => 8.99, 'sale_price' => null, 'sku' => 'NAIL-013', 'stock' => 75, 'is_featured' => false, 'image' => 'images/products/ongles-13.png'],
            ['name' => 'Ongles French Ombré – Nude dégradé blanc', 'slug' => 'ongles-french-ombre-nude', 'category' => 'ongles', 'description' => 'Set ongles artificiels French ombré : base nude rose avec dégradé vers pointe blanche. Formes coffin et ovale. Présentation premium.', 'price' => 9.99, 'sale_price' => null, 'sku' => 'NAIL-014', 'stock' => 68, 'is_featured' => true, 'image' => 'images/products/ongles-14.png'],
            ['name' => 'Sérums Visage – Ma Demoiselle elleBio, Pai Kalmer, La Canopée', 'slug' => 'serums-visage-ellebio-pai-canopee', 'category' => 'soins', 'description' => 'Sérum purifiant expert prébiotique, sérum apaisant aux céramides et sérum oléagineux nourrissant. Adaptés aux peaux sensibles.', 'price' => 89.00, 'sale_price' => null, 'sku' => 'SKIN-001', 'stock' => 30, 'is_featured' => true, 'image' => 'images/products/soin-1.png'],
            ['name' => 'Collection Soins – CeraVe, La Roche-Posay, The Ordinary', 'slug' => 'collection-soins-cerave-laroche-ordinary', 'category' => 'soins', 'description' => 'Lait hydratant CeraVe, gel moussant Effaclar, Niacinamide The Ordinary, Effaclar Duo, Vaseline, Cicaplast B5.', 'price' => 45.00, 'sale_price' => null, 'sku' => 'SKIN-002', 'stock' => 40, 'is_featured' => false, 'image' => 'images/products/soin-2.png'],
            ['name' => 'Sérum Visage BLESS au Squalane', 'slug' => 'serum-visage-bless-squalane', 'category' => 'soins', 'description' => 'Sérum visage avec squalane. 30 ml. Formule légère pour nourrir et protéger la peau. Flacon ambre avec pipette.', 'price' => 24.99, 'sale_price' => null, 'sku' => 'SKIN-003', 'stock' => 55, 'is_featured' => false, 'image' => 'images/products/soin-3.png'],
            ['name' => 'Collection Caudalie Resveratrol Lift – Sérum, Baume Regard, Fluide', 'slug' => 'collection-caudalie-resveratrol-lift', 'category' => 'soins', 'description' => 'Sérum fermeté, baume liftant regard et fluide liftant redensifiant SPF. Gamme Resveratrol [Lift] Caudalie Paris. Toutes peaux.', 'price' => 95.00, 'sale_price' => 79.99, 'sku' => 'SKIN-004', 'stock' => 25, 'is_featured' => true, 'image' => 'images/products/soin-4.png'],
            ['name' => 'Collection Soins Contour des Yeux – Vichy, Lancôme, Clinique', 'slug' => 'collection-soins-contour-yeux', 'category' => 'soins', 'description' => 'Correcteur yeux Vichy ProEVEN, Génifique Yeux Lancôme, Clinique Repairwear, Hevia Eye Complex, Murad Lighten & Brighten.', 'price' => 42.00, 'sale_price' => null, 'sku' => 'SKIN-005', 'stock' => 35, 'is_featured' => false, 'image' => 'images/products/soin-5.png'],
            ['name' => 'Sérum Vitamine C Dr. Rashel Brightening & Anti-Aging', 'slug' => 'serum-vitamine-c-dr-rashel', 'category' => 'soins', 'description' => 'Sérum visage vitamine C et acide hyaluronique. Anti-âge, éclat, fermeté. Testé dermatologiquement. Tous types de peaux.', 'price' => 34.99, 'sale_price' => null, 'sku' => 'SKIN-006', 'stock' => 50, 'is_featured' => true, 'image' => 'images/products/soin-6.png'],
            ['name' => 'Sérum Hydratant Anti-Âge Aura', 'slug' => 'serum-hydratant-anti-age-aura', 'category' => 'soins', 'description' => 'Sérum hydratant anti-âge. Texture dorée, application liftante. Flacon verre avec pipette.', 'price' => 29.99, 'sale_price' => null, 'sku' => 'SKIN-007', 'stock' => 60, 'is_featured' => false, 'image' => 'images/products/soin-7.png'],
            ['name' => 'Sérum Anti-Âge Rétinol OUHOE Rejuvenation', 'slug' => 'serum-retinol-ouhoe-anti-age', 'category' => 'soins', 'description' => 'Sérum rétinol doux anti-rides et bonne mine. Sans parabènes. 30 ml. Alternative douce au rétinol.', 'price' => 32.99, 'sale_price' => 28.99, 'sku' => 'SKIN-008', 'stock' => 45, 'is_featured' => true, 'image' => 'images/products/soin-8.png'],
            ['name' => 'Sérum Multi-Vitamines Miel & Venin d\'Abeille OUHOE', 'slug' => 'serum-multi-vitamines-ouhoe', 'category' => 'soins', 'description' => 'Sérum huile hydratant intense : venin d\'abeille, miel, vitamine A, squalane végétal, céramides. 30 ml. Peaux très sèches.', 'price' => 28.99, 'sale_price' => null, 'sku' => 'SKIN-009', 'stock' => 48, 'is_featured' => false, 'image' => 'images/products/soin-9.png'],
            ['name' => 'Sérum Acide Hyaluronique LAIKOU', 'slug' => 'serum-acide-hyaluronique-laikou', 'category' => 'soins', 'description' => 'Sérum acide hyaluronique hydratant. Affine les pores, répare. Texture légère. Flacon verre pipette.', 'price' => 22.99, 'sale_price' => null, 'sku' => 'SKIN-010', 'stock' => 65, 'is_featured' => false, 'image' => 'images/products/soin-10.png'],
            ['name' => 'Masque Tissu Garnier SkinActive Nutri Bomb Lait de Coco', 'slug' => 'masque-tissu-garnier-nutri-bomb', 'category' => 'soins', 'description' => 'Masque tissu nutrition intense et éclat. Lait de coco et acide hyaluronique. 15 min. Tissu d\'origine végétale. Dermatologiquement testé.', 'price' => 4.99, 'sale_price' => null, 'sku' => 'SKIN-011', 'stock' => 120, 'is_featured' => true, 'image' => 'images/products/soin-11.png'],
            ['name' => 'Masque Tissu Bio Republic Aloe Rescue Revitalisant', 'slug' => 'masque-tissu-biorepublic-aloe-rescue', 'category' => 'soins', 'description' => 'Masque en fibre revitalisant à la vitamine E. Tous types de peaux. Sans parabènes, cruauté free. 18 ml. Un masque usage unique.', 'price' => 5.99, 'sale_price' => null, 'sku' => 'SKIN-012', 'stock' => 90, 'is_featured' => false, 'image' => 'images/products/soin-12.png'],
            ['name' => 'Masque Bio-Cellulose Aloe Forever', 'slug' => 'masque-bio-cellulose-aloe-forever', 'category' => 'soins', 'description' => 'Masque visage bio-cellulose à l\'aloe. 25 g. Formule naturelle pour un teint frais et apaisé.', 'price' => 6.99, 'sale_price' => null, 'sku' => 'SKIN-013', 'stock' => 70, 'is_featured' => false, 'image' => 'images/products/soin-13.png'],
            ['name' => 'Avène Cleanance Gel Nettoyant Purifiant', 'slug' => 'avene-cleanance-gel-nettoyant', 'category' => 'soins', 'description' => 'Gel nettoyant visage et corps. Peaux mixtes, grasses, à imperfections. Purifie et matifie. 400 ml. Laboratoires dermatologiques.', 'price' => 14.99, 'sale_price' => null, 'sku' => 'SKIN-014', 'stock' => 80, 'is_featured' => false, 'image' => 'images/products/soin-14.png'],
            ['name' => 'Gel Nettoyant Visage Exceptionnelle Hydrapur', 'slug' => 'gel-nettoyant-exceptionnelle-hydrapur', 'category' => 'soins', 'description' => 'Gel nettoyant BHA/AHA, acide salicylique, vitamine C, thé vert. Perfecteur de teint, anti-taches, anti-acné, resserre les pores. Sans paraben, parfum, colorant, alcool, sulfate. Tous types de peaux.', 'price' => 18.99, 'sale_price' => null, 'sku' => 'SKIN-015', 'stock' => 55, 'is_featured' => true, 'image' => 'images/products/soin-15.png'],
            ['name' => 'Crème Visage Soin Naturel – Pot Verre', 'slug' => 'creme-visage-soin-naturel-pot', 'category' => 'soins', 'description' => 'Crème visage riche et onctueuse en pot verre. Texture luxueuse, ingrédients naturels. Pour un teint nourri et doux.', 'price' => 36.00, 'sale_price' => null, 'sku' => 'SKIN-016', 'stock' => 40, 'is_featured' => false, 'image' => 'images/products/soin-16.png'],
            ['name' => 'Set pinceaux maquillage professionnels – Vert & argent', 'slug' => 'set-pinceaux-pro-vert-argent', 'category' => 'accessoires', 'description' => 'Collection de pinceaux visage et yeux : poudre, blush, fond de teint, fard, eyeliner. Manches verts/bleutés, viroles argentées. Perles et fond de teint inclus pour démo.', 'price' => 49.90, 'sale_price' => null, 'sku' => 'ACC-001', 'stock' => 35, 'is_featured' => true, 'image' => 'images/products/acces-1.png'],
            ['name' => 'Set pinceaux maquillage complet – Manches violet', 'slug' => 'set-pinceaux-complet-violet', 'category' => 'accessoires', 'description' => 'Environ 28 à 30 pinceaux : poudre, fond de teint, fard à paupières, blending, eyeliner, spoolie. Poils noirs, viroles argent, manches violet foncé.', 'price' => 54.90, 'sale_price' => 47.90, 'sku' => 'ACC-002', 'stock' => 28, 'is_featured' => true, 'image' => 'images/products/acces-2.png'],
            ['name' => 'Set 7 pinceaux Boozyshop – Marbre & rose gold', 'slug' => 'set-7-pinceaux-boozyshop-marbre', 'category' => 'accessoires', 'description' => 'Sept pinceaux visage et yeux : angled, dôme, blending. Poils blanc/gris, viroles rose gold, manches marbre blanc et noir. Boozyshop.', 'price' => 39.90, 'sale_price' => null, 'sku' => 'ACC-003', 'stock' => 45, 'is_featured' => true, 'image' => 'images/products/acces-3.png'],
            ['name' => 'Set pinceaux maquillage – Manches blanc & or', 'slug' => 'set-pinceaux-blanc-or', 'category' => 'accessoires', 'description' => 'Environ 30 à 35 pinceaux : visage (poudre, blush, fond de teint), yeux et précision. Poils beige/rose, viroles dorées, manches blanc cassé.', 'price' => 52.00, 'sale_price' => null, 'sku' => 'ACC-004', 'stock' => 30, 'is_featured' => true, 'image' => 'images/products/acces-4.png'],
            ['name' => 'Kit extensions de cils – Outils rose & or', 'slug' => 'kit-extensions-cils-outils-rose-or', 'category' => 'accessoires', 'description' => 'Coffret extensions de cils : pinces rose à pointes or, miroir à main, brosses spiral, étuis à cils numérotés. Style professionnel rose et or.', 'price' => 34.90, 'sale_price' => null, 'sku' => 'ACC-005', 'stock' => 40, 'is_featured' => false, 'image' => 'images/products/acces-5.png'],
            ['name' => 'Kit manucure & soins – Outils argent & rose', 'slug' => 'kit-manucure-soins-argent-rose', 'category' => 'accessoires', 'description' => 'Spatules, pinces, ciseaux, lime à pieds, flacons et sérums. Outils manucure, pédicure et soins. Présentation soignée sur fond blanc.', 'price' => 44.90, 'sale_price' => null, 'sku' => 'ACC-006', 'stock' => 38, 'is_featured' => false, 'image' => 'images/products/acces-6.png'],
            ['name' => 'Coffret manucure pédicure rose – Complet', 'slug' => 'coffret-manucure-pedicure-rose', 'category' => 'accessoires', 'description' => 'Trousse manucure/pédicure : coupe-ongles, ciseaux, lime, repousse-cuticules, pince à épiler. Manches rose, acier inoxydable. Coffret rigide rose et argent.', 'price' => 29.90, 'sale_price' => null, 'sku' => 'ACC-007', 'stock' => 55, 'is_featured' => true, 'image' => 'images/products/acces-7.png'],
            ['name' => 'Set outils sourcils et cils – Noir', 'slug' => 'set-outils-sourcils-cils-noir', 'category' => 'accessoires', 'description' => 'Brosse/peigne sourcils, séparateur de cils, pinceau angle + spoolie, rasoir sourcils. Manches noirs. Pour regard précis et soigné.', 'price' => 18.90, 'sale_price' => null, 'sku' => 'ACC-008', 'stock' => 70, 'is_featured' => false, 'image' => 'images/products/acces-8.png'],
            ['name' => 'Set pinceaux fond de teint & précision – Noir', 'slug' => 'set-pinceaux-fond-teint-precision', 'category' => 'accessoires', 'description' => 'Trois pinceaux angle (grand, moyen, précision) et nuancier fond de teint. Démonstration application. Idéal pour un teint impeccable.', 'price' => 36.90, 'sale_price' => null, 'sku' => 'ACC-009', 'stock' => 42, 'is_featured' => true, 'image' => 'images/products/acces-9.png'],
            ['name' => 'Éponges maquillage Electric Violet', 'slug' => 'eponges-maquillage-electric-violet', 'category' => 'accessoires', 'description' => 'Éponges de blend teardrop magenta et violet. Pot cylindrique « Electric Violet ». Application fond de teint et correcteur fluide.', 'price' => 14.90, 'sale_price' => null, 'sku' => 'ACC-010', 'stock' => 90, 'is_featured' => true, 'image' => 'images/products/acces-10.png'],
            ['name' => 'Éponges blend – Nude, jaune & fuchsia', 'slug' => 'eponges-blend-nude-jaune-fuchsia', 'category' => 'accessoires', 'description' => 'Trois éponges maquillage teardrop : nude, jaune et fuchsia. Texture douce, fond tissu clair. Pour fond de teint et correction.', 'price' => 12.90, 'sale_price' => null, 'sku' => 'ACC-011', 'stock' => 85, 'is_featured' => false, 'image' => 'images/products/acces-11.png'],
            ['name' => 'Rouleau et Gua Sha visage – Quartz rose & jade', 'slug' => 'roller-gua-sha-quartz-jade', 'category' => 'accessoires', 'description' => 'Deux rouleaux visage (quartz rose et jade) et deux Gua Sha (cœur rose, croissant vert). Pierre naturelle polie, finitions or. Décongestion et drainage.', 'price' => 32.90, 'sale_price' => 27.90, 'sku' => 'ACC-012', 'stock' => 50, 'is_featured' => true, 'image' => 'images/products/acces-12.png'],
            ['name' => 'Rouleaux visage jade & quartz rose – Double tête or', 'slug' => 'rouleaux-visage-jade-quartz-rose', 'category' => 'accessoires', 'description' => 'Deux rouleaux massage visage double tête : jade vert et quartz rose. Monture dorée. Avec flacon pipette et bol. Soin et drainage.', 'price' => 38.90, 'sale_price' => null, 'sku' => 'ACC-013', 'stock' => 35, 'is_featured' => true, 'image' => 'images/products/acces-13.png'],
            ['name' => 'Trousse voyage soins – Gris clair', 'slug' => 'trousse-voyage-soins-gris', 'category' => 'accessoires', 'description' => 'Trousse zippée gris clair : brosse poils clairs, peigne, ciseaux, coupe-ongles, bâtonnet cuticules, limes, flacon. Idéal voyage et quotidien.', 'price' => 24.90, 'sale_price' => null, 'sku' => 'ACC-014', 'stock' => 60, 'is_featured' => false, 'image' => 'images/products/acces-14.png'],
        ];

        foreach ($products as $data) {
            $cat = $categories->get($data['category']);
            if (!$cat) continue;

            $slug = $data['slug'];
            $sku = $data['sku'];
            $image = $data['image'] ?? null;

            unset($data['category'], $data['image']);
            Product::updateOrCreate(
                ['sku' => $sku],
                [
                    'category_id' => $cat->id,
                    'name' => $data['name'],
                    'slug' => $slug,
                    'description' => $data['description'],
                    'price' => $data['price'],
                    'sale_price' => $data['sale_price'],
                    'sku' => $sku,
                    'stock' => $data['stock'],
                    'image' => $image,
                    'is_active' => true,
                    'is_featured' => $data['is_featured'],
                ]
            );
        }
    }
}
